config/routes.rb
Treebook::Application.routes.draw do
  resources :cuarteles

  resources :campos

  resources :personas

  resources :seguimiento_historials

  resources :rols

  resources :mantenedors

  get "naviera/apl"
  get "home/index"
  get 'naviera/cma'
  get 'naviera/vessel'
  get 'naviera/nyk'
  get "profiles/show"
  
  
  resources :statuses
  get "feed", :to => "statuses#index", :as => :feed
  root to: 'home#index'

  as :user do
    get "/register", :to => "devise/registrations#new", :as => :register
    get "/login", :to => "devise/sessions#new", :as => :login
    get "/logout", :to => "devise/sessions#destroy", :as => :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  get '/:id', to: "profiles#show", as: 'profile'
  get 'actualizar/:id', to: "seguimientos#actualizar", as: 'actualizar'
  resources :user_friendships

end

app/models/campo.rb
class Campo < ActiveRecord::Base
   belongs_to :persona
   has_many :cuartele, dependent: :destroy
end

app/models/cuartele.rb
class Cuartele < ActiveRecord::Base
  belongs_to :persona
  belongs_to :campo
end

app/models/mantenedor.rb
class Mantenedor < ActiveRecord::Base
  def self.navieras
    Mantenedor.where(:tipo => :naviera).order(:id)
  end
  def self.tipo_personas
    Mantenedor.where(:tipo => :tipo_persona).order(:id)
  end
  
  def self.paises
    Mantenedor.where(:tipo => :pais).order(:id)
  end
end

app/models/persona.rb
class Persona < ActiveRecord::Base
  has_many :campos, dependent: :destroy
end

app/models/rol.rb
class Rol < ActiveRecord::Base
end

app/models/status.rb
class Status < ActiveRecord::Base
	belongs_to :user

	validates :content, { presence: :true, length: { minimum: 2 }}
	validates :user, { presence: true }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  has_many :statuses
  has_many :user_friendships
  has_many :friends, through: :user_friendships

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :profile_name, presence: true, 
                           uniqueness: true,
                           format: {
                             with: /\A[a-zA-Z\-\_]+\Z/,
                             message: "Must be formatted correctly."
                           }

  def full_name
  	first_name + ' ' + last_name
  end

  def gravatar_url
    gravatar_email = email.strip
    downcased_email = gravatar_email.downcase
    hash = Digest::MD5.hexdigest(downcased_email)
    "http://www.gravatar.com/avatar/#{hash}"
  end

  def to_param
    profile_name
  end
end

app/models/user_friendship.rb
class UserFriendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: 'User', foreign_key: 'friend_id'
end

app/controllers/campos_controller.rb
class CamposController < ApplicationController
  before_action :set_campo, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @campos = Campo.all
    respond_with(@campos)
  end

  def show
    respond_with(@campo)
  end

  def new
    @campo = Campo.new
    respond_with(@campo)
  end

  def edit
  end

  def create
    @campo = Campo.new(campo_params)
    @campo.save
    respond_with(@campo)
  end

  def update
    @campo.update(campo_params)
    respond_with(@campo)
  end

  def destroy
    @campo.destroy
    respond_with(@campo)
  end

  private
    def set_campo
      @campo = Campo.find(params[:id])
    end

    def campo_params
      params.require(:campo).permit(:nombre)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  before_action :authenticate_user!
  before_action :set_persona, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @personas = Persona.all
    respond_with(@personas)
  end

  def show
    respond_with(@persona)
  end

  def new
    @persona = Persona.new
    respond_with(@persona)
  end

  def edit
  end

  def create
    @persona = Persona.new(persona_params)
    @persona.save
    respond_with(@persona)
  end

  def update
    @persona.update(persona_params)
    respond_with(@persona)
  end

  def destroy
    @persona.destroy
    respond_with(@persona)
  end

  private
    def set_persona
      @persona = Persona.find(params[:id])
    end

    def persona_params
      params.require(:persona).permit(:rut, :dv, :tipo, :estado, :razonsocial, :alias, :nacionalidad, :direccion, :email, :contacto, :user)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	def show
		@user = User.find_by_profile_name(params[:id])
		if (@user)
      @statuses = @user.statuses
			render action: :show
    else
      render file: 'public/404', status: 404, formats: [:html]
    end
  end
end

app/controllers/rols_controller.rb
class RolsController < ApplicationController
  before_action :set_rol, only: [:show, :edit, :update, :destroy]

  # GET /rols
  # GET /rols.json
  def index
    @rols = Rol.all
  end

  # GET /rols/1
  # GET /rols/1.json
  def show
  end

  # GET /rols/new
  def new
    @rol = Rol.new
  end

  # GET /rols/1/edit
  def edit
  end

  # POST /rols
  # POST /rols.json
  def create
    @rol = Rol.new(rol_params)

    respond_to do |format|
      if @rol.save
        format.html { redirect_to @rol, notice: 'Rol was successfully created.' }
        format.json { render action: 'show', status: :created, location: @rol }
      else
        format.html { render action: 'new' }
        format.json { render json: @rol.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rols/1
  # PATCH/PUT /rols/1.json
  def update
    respond_to do |format|
      if @rol.update(rol_params)
        format.html { redirect_to @rol, notice: 'Rol was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @rol.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rols/1
  # DELETE /rols/1.json
  def destroy
    @rol.destroy
    respond_to do |format|
      format.html { redirect_to rols_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rol
      @rol = Rol.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rol_params
      params.require(:rol).permit(:nombre)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # genera un select con los datos del mantenedor
    def manten(f, campo, datos, prompt = nil, opciones = {})
      if prompt
        f.collection_select campo, datos, :valor, :valor, {:prompt => prompt}, opciones
      else
       f.collection_select campo, datos, :valor, :valor, {}, opciones
      end
    end
  
	def flash_class(type)
		case type
		when :alert
			"alert-danger"
		when :notice
			"alert-success"
		else
			""
		end
	end
end

app/helpers/campos_helper.rb
module CamposHelper
end

app/helpers/cuarteles_helper.rb
module CuartelesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mantenedors_helper.rb
module MantenedorsHelper
end

app/helpers/naviera_helper.rb
module NavieraHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/rols_helper.rb
module RolsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/campos/_form.html.erb
<%= simple_form_for(@campo) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nombre %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/campos/edit.html.erb
<h1>Editing campo</h1>

<%= render 'form' %>

<%= link_to 'Show', @campo %> |
<%= link_to 'Back', campos_path %>

app/views/campos/index.html.erb
<h1>Listing campos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @campos.each do |campo| %>
      <tr>
        <td><%= campo.nombre %></td>
        <td><%= link_to 'Show', campo %></td>
        <td><%= link_to 'Edit', edit_campo_path(campo) %></td>
        <td><%= link_to 'Destroy', campo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Campo', new_campo_path %>

app/views/campos/new.html.erb
<h1>New campo</h1>

<%= render 'form' %>

<%= link_to 'Back', campos_path %>

app/views/campos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @campo.nombre %>
</p>

<%= link_to 'Edit', edit_campo_path(@campo) %> |
<%= link_to 'Back', campos_path %>

app/views/personas/_form.html.erb
<%= simple_form_for(@persona) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
	  
	  <table>
	  	<tr>
	  		<td>RUT</td>
			<td><%= f.text_field:rut %></td>
			<td>DV</td>
			<td><%= f.text_field:dv %></td>
			<td>Tipo</td>
			<td><%= manten f, :tipo, Mantenedor.tipo_personas, 'Seleccione Tipo de Persona'%></td>
			<td>ESTADO</td>
			<td><%= f.text_field:estado %></td>
	  	</tr>
	  	<tr>
	  		<td>Razon Social</td>
			<td><%= f.text_field:razonsocial %></td>
			<td>Alias</td>
			<td><%= f.text_field:alias %></td>
			<td>Nacionalidad</td>
			<td><%= manten f, :nacionalidad, Mantenedor.paises, 'Seleccione País'%></td>
			<td>Dirección</td>
			<td><%= f.text_field:direccion %></td>
	  	</tr>
	  	<tr>
	  		<td>E-Mail</td>
			<td><%= f.text_field:email %></td>
			<td>Contacto</td>
			<td><%= f.text_field:contacto %></td>
			<td>Usuario</td>
			<td><%= f.text_field:user %></td>
			
	  	</tr>
	  </table>
    
    
    
   
   

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/personas/edit.html.erb
<h1>Modificar Persona</h1>

<%= render 'form' %>

<%= link_to 'Ver', @persona %> |
<%= link_to 'Volver', personas_path %>

app/views/personas/index.html.erb
<h1>Listado de Personas</h1>

<table border="1">
  <thead>
    <tr>
      <th>Rut</th>
      <th>Dv</th>
      <th>Tipo</th>
      <th>Estado</th>
      <th>Razonsocial</th>
      <th>Alias</th>
      <th>Nacionalidad</th>
      <th>Direccion</th>
      <th>Email</th>
      <th>Contacto</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @personas.each do |persona| %>
      <tr>
        <td><%= persona.rut %></td>
        <td><%= persona.dv %></td>
        <td><%= persona.tipo %></td>
        <td><%= persona.estado %></td>
        <td><%= persona.razonsocial %></td>
        <td><%= persona.alias %></td>
        <td><%= persona.nacionalidad %></td>
        <td><%= persona.direccion %></td>
        <td><%= persona.email %></td>
        <td><%= persona.contacto %></td>
        <td><%= persona.user %></td>
        <td><%= link_to 'Ver', persona %></td>
        <td><%= link_to 'Editar', edit_persona_path(persona) %></td>
        <td><%= link_to 'Eliminar', persona, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Persona', new_persona_path %>

app/views/personas/new.html.erb
<h1>Agregar Nueva Persona</h1>

<%= render 'form' %>

<%= link_to 'Back', personas_path %>

app/views/personas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rut:</strong>
  <%= @persona.rut %>
</p>

<p>
  <strong>Dv:</strong>
  <%= @persona.dv %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @persona.tipo %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @persona.estado %>
</p>

<p>
  <strong>Razonsocial:</strong>
  <%= @persona.razonsocial %>
</p>

<p>
  <strong>Alias:</strong>
  <%= @persona.alias %>
</p>

<p>
  <strong>Nacionalidad:</strong>
  <%= @persona.nacionalidad %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @persona.direccion %>
</p>

<p>
  <strong>Email:</strong>
  <%= @persona.email %>
</p>

<p>
  <strong>Contacto:</strong>
  <%= @persona.contacto %>
</p>

<p>
  <strong>User:</strong>
  <%= @persona.user %>
</p>

<h2>campos </h2>

<% @persona.campos.each do |campo| %>
<p>
  <strong>Nombre Campo:</strong>
  <%= campo.nombre %>
</p>
<%end%>



<%= link_to 'Edit', edit_persona_path(@persona) %> |
<%= link_to 'Back', personas_path %>