config/routes.rb
Treebook::Application.routes.draw do
  resources :cuarteles

  resources :campos

  resources :personas

  resources :seguimiento_historials

  resources :rols

  resources :mantenedors

  get "naviera/apl"
  get "home/index"
  get 'naviera/cma'
  get 'naviera/vessel'
  get 'naviera/nyk'
  get "profiles/show"
  
  
  resources :statuses
  get "feed", :to => "statuses#index", :as => :feed
  root to: 'home#index'

  as :user do
    get "/register", :to => "devise/registrations#new", :as => :register
    get "/login", :to => "devise/sessions#new", :as => :login
    get "/logout", :to => "devise/sessions#destroy", :as => :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  get '/:id', to: "profiles#show", as: 'profile'
  get 'actualizar/:id', to: "seguimientos#actualizar", as: 'actualizar'
  resources :user_friendships

end

app/models/mantenedor.rb
class Mantenedor < ActiveRecord::Base
  def self.navieras
    Mantenedor.where(:tipo => :naviera).order(:id)
  end
  def self.tipo_personas
    Mantenedor.where(:tipo => :tipo_persona).order(:id)
  end
  
  def self.paises
    Mantenedor.where(:tipo => :pais).order(:id)
  end
end

app/controllers/mantenedors_controller.rb
class MantenedorsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_mantenedor, only: [:show, :edit, :update, :destroy]

  # GET /mantenedors
  # GET /mantenedors.json
  def index
    @mantenedors = Mantenedor.all
  end

  # GET /mantenedors/1
  # GET /mantenedors/1.json
  def show
  end

  # GET /mantenedors/new
  def new
    @mantenedor = Mantenedor.new
  end

  # GET /mantenedors/1/edit
  def edit
  end

  # POST /mantenedors
  # POST /mantenedors.json
  def create
    @mantenedor = Mantenedor.new(mantenedor_params)

    respond_to do |format|
      if @mantenedor.save
        format.html { redirect_to @mantenedor, notice: 'Mantenedor was successfully created.' }
        format.json { render action: 'show', status: :created, location: @mantenedor }
      else
        format.html { render action: 'new' }
        format.json { render json: @mantenedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mantenedors/1
  # PATCH/PUT /mantenedors/1.json
  def update
    respond_to do |format|
      if @mantenedor.update(mantenedor_params)
        format.html { redirect_to @mantenedor, notice: 'Mantenedor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @mantenedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mantenedors/1
  # DELETE /mantenedors/1.json
  def destroy
    @mantenedor.destroy
    respond_to do |format|
      format.html { redirect_to mantenedors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mantenedor
      @mantenedor = Mantenedor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mantenedor_params
      params.require(:mantenedor).permit(:tipo, :valor, :misc, :codigo)
    end
end

app/helpers/mantenedors_helper.rb
module MantenedorsHelper
end

app/views/mantenedors/_form.html.erb
<%= simple_form_for(@mantenedor) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :tipo %>
    <%= f.input :valor %>
    <%= f.input :misc %>
    <%= f.input :codigo %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/mantenedors/edit.html.erb
<h1>Editing mantenedor</h1>

<%= render 'form' %>

<%= link_to 'Show', @mantenedor %> |
<%= link_to 'Back', mantenedors_path %>

app/views/mantenedors/index.html.erb
<h1>Códigos de Administración</h1>

<table class="table">
  <thead>
    <tr>
      <th>Tipo</th>
      <th>Valor</th>
      <th>Misc</th>
      <th>Codigo</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @mantenedors.each do |mantenedor| %>
      <tr>
        <td><%= mantenedor.tipo %></td>
        <td><%= mantenedor.valor %></td>
        <td><%= mantenedor.misc %></td>
        <td><%= mantenedor.codigo %></td>
        <td><%= link_to 'Show', mantenedor %></td>
        <td><%= link_to 'Edit', edit_mantenedor_path(mantenedor) %></td>
        <td><%= link_to 'Destroy', mantenedor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mantenedor', new_mantenedor_path %>

app/views/mantenedors/new.html.erb
<h1>New mantenedor</h1>

<%= render 'form' %>

<%= link_to 'Back', mantenedors_path %>

app/views/mantenedors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo:</strong>
  <%= @mantenedor.tipo %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @mantenedor.valor %>
</p>

<p>
  <strong>Misc:</strong>
  <%= @mantenedor.misc %>
</p>

<p>
  <strong>Codigo:</strong>
  <%= @mantenedor.codigo %>
</p>

<%= link_to 'Edit', edit_mantenedor_path(@mantenedor) %> |
<%= link_to 'Back', mantenedors_path %>