config/routes.rb
Treebook::Application.routes.draw do
  resources :cuarteles

  resources :campos

  resources :personas

  resources :seguimiento_historials

  resources :rols

  resources :mantenedors

  get "naviera/apl"
  get "home/index"
  get 'naviera/cma'
  get 'naviera/vessel'
  get 'naviera/nyk'
  get "profiles/show"
  
  
  resources :statuses
  get "feed", :to => "statuses#index", :as => :feed
  root to: 'home#index'

  as :user do
    get "/register", :to => "devise/registrations#new", :as => :register
    get "/login", :to => "devise/sessions#new", :as => :login
    get "/logout", :to => "devise/sessions#destroy", :as => :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  get '/:id', to: "profiles#show", as: 'profile'
  get 'actualizar/:id', to: "seguimientos#actualizar", as: 'actualizar'
  resources :user_friendships

end

app/models/campo.rb
class Campo < ActiveRecord::Base
   belongs_to :persona
   has_many :cuartele, dependent: :destroy
end

app/models/cuartele.rb
class Cuartele < ActiveRecord::Base
  belongs_to :persona
  belongs_to :campo
end

app/models/mantenedor.rb
class Mantenedor < ActiveRecord::Base
  def self.navieras
    Mantenedor.where(:tipo => :naviera).order(:id)
  end
  def self.tipo_personas
    Mantenedor.where(:tipo => :tipo_persona).order(:id)
  end
  
  def self.paises
    Mantenedor.where(:tipo => :pais).order(:id)
  end
end

app/models/persona.rb
class Persona < ActiveRecord::Base
  has_many :campos, dependent: :destroy
end

app/models/rol.rb
class Rol < ActiveRecord::Base
end

app/models/status.rb
class Status < ActiveRecord::Base
	belongs_to :user

	validates :content, { presence: :true, length: { minimum: 2 }}
	validates :user, { presence: true }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  has_many :statuses
  has_many :user_friendships
  has_many :friends, through: :user_friendships

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :profile_name, presence: true, 
                           uniqueness: true,
                           format: {
                             with: /\A[a-zA-Z\-\_]+\Z/,
                             message: "Must be formatted correctly."
                           }

  def full_name
  	first_name + ' ' + last_name
  end

  def gravatar_url
    gravatar_email = email.strip
    downcased_email = gravatar_email.downcase
    hash = Digest::MD5.hexdigest(downcased_email)
    "http://www.gravatar.com/avatar/#{hash}"
  end

  def to_param
    profile_name
  end
end

app/models/user_friendship.rb
class UserFriendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: 'User', foreign_key: 'friend_id'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/rols_controller.rb
class RolsController < ApplicationController
  before_action :set_rol, only: [:show, :edit, :update, :destroy]

  # GET /rols
  # GET /rols.json
  def index
    @rols = Rol.all
  end

  # GET /rols/1
  # GET /rols/1.json
  def show
  end

  # GET /rols/new
  def new
    @rol = Rol.new
  end

  # GET /rols/1/edit
  def edit
  end

  # POST /rols
  # POST /rols.json
  def create
    @rol = Rol.new(rol_params)

    respond_to do |format|
      if @rol.save
        format.html { redirect_to @rol, notice: 'Rol was successfully created.' }
        format.json { render action: 'show', status: :created, location: @rol }
      else
        format.html { render action: 'new' }
        format.json { render json: @rol.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rols/1
  # PATCH/PUT /rols/1.json
  def update
    respond_to do |format|
      if @rol.update(rol_params)
        format.html { redirect_to @rol, notice: 'Rol was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @rol.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rols/1
  # DELETE /rols/1.json
  def destroy
    @rol.destroy
    respond_to do |format|
      format.html { redirect_to rols_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rol
      @rol = Rol.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rol_params
      params.require(:rol).permit(:nombre)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # genera un select con los datos del mantenedor
    def manten(f, campo, datos, prompt = nil, opciones = {})
      if prompt
        f.collection_select campo, datos, :valor, :valor, {:prompt => prompt}, opciones
      else
       f.collection_select campo, datos, :valor, :valor, {}, opciones
      end
    end
  
	def flash_class(type)
		case type
		when :alert
			"alert-danger"
		when :notice
			"alert-success"
		else
			""
		end
	end
end

app/helpers/campos_helper.rb
module CamposHelper
end

app/helpers/cuarteles_helper.rb
module CuartelesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mantenedors_helper.rb
module MantenedorsHelper
end

app/helpers/naviera_helper.rb
module NavieraHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/rols_helper.rb
module RolsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>AgroPRO</title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<a class="navbar-brand" href="#">AgroPRO</a>
			</div>
			
			<ul class="nav navbar-nav">
				<% if user_signed_in? %>
				<li><%= link_to 'Home', root_path, { :class=>"navbar-brand" }  %></li>
				<li><%= link_to 'Personas', personas_path, { :class=>"navbar-brand" }  %></li>
				<li><%= link_to 'Campos', campos_path, { :class=>"navbar-brand" }  %></li>
				<li><%= link_to 'Cuarteles', cuarteles_path, { :class=>"navbar-brand" }  %></li>
				<li><%= link_to 'Mantenedores', mantenedors_path, { :class=>"navbar-brand" }  %></li>
				
				<%end%>
				
			</ul>
			
			
			
			
			
			
			
			<ul class="nav navbar-nav navbar-right">
				<% if user_signed_in? %>
				
				<li><%= link_to current_user.full_name, edit_user_registration_path %></li>
				<li><%= link_to "Log Out", logout_path %></li>
				<% else %>
				<li><%= link_to "Sign In", login_path %></li>
				<li><%= link_to "Register", register_path %></li>
				<% end %>
			</ul>
		</div>
	</div>
	<div class="container">
		<% flash.each do |type, message| %>
		<div class="alert <%= flash_class type %> alert-dismissable">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			<p><%= message %></p>
		</div>
		<% end %>
		<%= yield %>
	</div>
</body>
</html>